/*
 * Arad SMS Core Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets DataCodings
 */
@JsonAdapter(DataCodings.Adapter.class)
public enum DataCodings {
  /*
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),
  NUMBER_null(null),

   */
  NUMBER_null(null);

  private Integer value;

  DataCodings(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DataCodings fromValue(String text) {
    for (DataCodings b : DataCodings.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<DataCodings> {
    @Override
    public void write(final JsonWriter jsonWriter, final DataCodings enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DataCodings read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return DataCodings.fromValue(String.valueOf(value));
    }
  }
}
