/*
 * Arad SMS Core Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets MessageClass
 */
@JsonAdapter(MessageClass.Adapter.class)
public enum MessageClass {


  NUMBER_TEXT(null),
  NUMBER_BINARY(null),
  NUMBER_WAPPUSH(null),
  NUMBER_VCALENDAR(null),
  NUMBER_VOICEMAIL(null),
  NUMBER_EMAIL(null),
  NUMBER_FAX(null),
  NUMBER_VIDEO(null),
  NUMBER_PICTUREMESSAGE(null),
  NUMBER_USSD(null),
  NUMBER_MMS(null),
  NUMBER_FLASH(null),
  NUMBER_HEXSTRING(null),
  NUMBER_VCARD(null);
  private Integer value;

  MessageClass(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static MessageClass fromValue(String text) {
    for (MessageClass b : MessageClass.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<MessageClass> {
    @Override
    public void write(final JsonWriter jsonWriter, final MessageClass enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public MessageClass read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return MessageClass.fromValue(String.valueOf(value));
    }
  }
}
