/*
 * Arad SMS Core Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Priority
 */
@JsonAdapter(Priority.Adapter.class)
public enum Priority {


  Lowest(null),
  VeryLow(null),
  Low(null),
  Normal(null),
  AboveNormal(null),
  High(null),
  VeryHigh(null),
  Highest(null);


  private Integer value;

  Priority(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Priority fromValue(String text) {
    for (Priority b : Priority.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Priority> {
    @Override
    public void write(final JsonWriter jsonWriter, final Priority enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Priority read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return Priority.fromValue(String.valueOf(value));
    }
  }
}
