/*
 * Arad SMS Core Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package arad.sms.core.javaclient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * AradBulkMessage
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-31T13:23:41.190784500+03:30[GMT+03:30]")
public class AradBulkMessage {
  @SerializedName("sourceAddress")
  private String sourceAddress = null;

  @SerializedName("destinationAddress")
  private List<String> destinationAddress = null;

  @SerializedName("validityPeriod")
  private OffsetDateTime validityPeriod = null;

  @SerializedName("messageText")
  private String messageText = null;

  @SerializedName("serviceID")
  private String serviceID = null;

  @SerializedName("servicePrice")
  private Double servicePrice = null;

  @SerializedName("targetUDH")
  private List<String> targetUDH = null;

  public AradBulkMessage sourceAddress(String sourceAddress) {
    this.sourceAddress = sourceAddress;
    return this;
  }

   /**
   * Get sourceAddress
   * @return sourceAddress
  **/
  @Schema(description = "")
  public String getSourceAddress() {
    return sourceAddress;
  }

  public void setSourceAddress(String sourceAddress) {
    this.sourceAddress = sourceAddress;
  }

  public AradBulkMessage destinationAddress(List<String> destinationAddress) {
    this.destinationAddress = destinationAddress;
    return this;
  }

  public AradBulkMessage addDestinationAddressItem(String destinationAddressItem) {
    if (this.destinationAddress == null) {
      this.destinationAddress = new ArrayList<String>();
    }
    this.destinationAddress.add(destinationAddressItem);
    return this;
  }

   /**
   * Get destinationAddress
   * @return destinationAddress
  **/
  @Schema(description = "")
  public List<String> getDestinationAddress() {
    return destinationAddress;
  }

  public void setDestinationAddress(List<String> destinationAddress) {
    this.destinationAddress = destinationAddress;
  }

  public AradBulkMessage validityPeriod(OffsetDateTime validityPeriod) {
    this.validityPeriod = validityPeriod;
    return this;
  }

   /**
   * Get validityPeriod
   * @return validityPeriod
  **/
  @Schema(description = "")
  public OffsetDateTime getValidityPeriod() {
    return validityPeriod;
  }

  public void setValidityPeriod(OffsetDateTime validityPeriod) {
    this.validityPeriod = validityPeriod;
  }

  public AradBulkMessage messageText(String messageText) {
    this.messageText = messageText;
    return this;
  }

   /**
   * Get messageText
   * @return messageText
  **/
  @Schema(description = "")
  public String getMessageText() {
    return messageText;
  }

  public void setMessageText(String messageText) {
    this.messageText = messageText;
  }

  public AradBulkMessage serviceID(String serviceID) {
    this.serviceID = serviceID;
    return this;
  }

   /**
   * Get serviceID
   * @return serviceID
  **/
  @Schema(description = "")
  public String getServiceID() {
    return serviceID;
  }

  public void setServiceID(String serviceID) {
    this.serviceID = serviceID;
  }

  public AradBulkMessage servicePrice(Double servicePrice) {
    this.servicePrice = servicePrice;
    return this;
  }

   /**
   * Get servicePrice
   * @return servicePrice
  **/
  @Schema(description = "")
  public Double getServicePrice() {
    return servicePrice;
  }

  public void setServicePrice(Double servicePrice) {
    this.servicePrice = servicePrice;
  }

  public AradBulkMessage targetUDH(List<String> targetUDH) {
    this.targetUDH = targetUDH;
    return this;
  }

  public AradBulkMessage addTargetUDHItem(String targetUDHItem) {
    if (this.targetUDH == null) {
      this.targetUDH = new ArrayList<String>();
    }
    this.targetUDH.add(targetUDHItem);
    return this;
  }

   /**
   * Get targetUDH
   * @return targetUDH
  **/
  @Schema(description = "")
  public List<String> getTargetUDH() {
    return targetUDH;
  }

  public void setTargetUDH(List<String> targetUDH) {
    this.targetUDH = targetUDH;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AradBulkMessage aradBulkMessage = (AradBulkMessage) o;
    return Objects.equals(this.sourceAddress, aradBulkMessage.sourceAddress) &&
        Objects.equals(this.destinationAddress, aradBulkMessage.destinationAddress) &&
        Objects.equals(this.validityPeriod, aradBulkMessage.validityPeriod) &&
        Objects.equals(this.messageText, aradBulkMessage.messageText) &&
        Objects.equals(this.serviceID, aradBulkMessage.serviceID) &&
        Objects.equals(this.servicePrice, aradBulkMessage.servicePrice) &&
        Objects.equals(this.targetUDH, aradBulkMessage.targetUDH);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceAddress, destinationAddress, validityPeriod, messageText, serviceID, servicePrice, targetUDH);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AradBulkMessage {\n");
    
    sb.append("    sourceAddress: ").append(toIndentedString(sourceAddress)).append("\n");
    sb.append("    destinationAddress: ").append(toIndentedString(destinationAddress)).append("\n");
    sb.append("    validityPeriod: ").append(toIndentedString(validityPeriod)).append("\n");
    sb.append("    messageText: ").append(toIndentedString(messageText)).append("\n");
    sb.append("    serviceID: ").append(toIndentedString(serviceID)).append("\n");
    sb.append("    servicePrice: ").append(toIndentedString(servicePrice)).append("\n");
    sb.append("    targetUDH: ").append(toIndentedString(targetUDH)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
