/*
 * Arad SMS Core Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package arad.sms.core.javaclient.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets MessageClass
 */
@JsonAdapter(MessageClass.Adapter.class)
public enum MessageClass {

  TEXT(0),
  BINARY(1),
  WAPPUSH(2),
  VCALENDAR(3),
  VOICEMAIL(4),
  EMAIL(5),
  FAX(6),
  VIDEO(7),
  PICTUREMESSAGE(8),
  USSD(9),
  MMS(10),
  FLASH(11),
  HEXSTRING(12),
  VCARD(13);



  
  private Integer value;

  MessageClass(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static MessageClass fromValue(String text) {
    for (MessageClass b : MessageClass.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<MessageClass> {
    @Override
    public void write(final JsonWriter jsonWriter, final MessageClass enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public MessageClass read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return MessageClass.fromValue(String.valueOf(value));
    }
  }
}
