/*
 * Arad SMS Core Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AradA2PMessage;
import io.swagger.client.model.AradBulkMessage;
import org.threeten.bp.OffsetDateTime;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MessageApi
 */
@Ignore
public class MessageApiTest {

    private final MessageApi api = new MessageApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiMessageBulkPostTest() throws ApiException {
        AradBulkMessage body = null;
        Boolean returnLongId = null;
        String apiVersion = null;
        api.apiMessageBulkPost(body, returnLongId, apiVersion);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiMessageGetDLRPostTest() throws ApiException {
        List<String> body = null;
        Boolean returnLongId = null;
        Boolean returnUDH = null;
        String apiVersion = null;
        api.apiMessageGetDLRPost(body, returnLongId, returnUDH, apiVersion);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiMessageGetMOByDateGetTest() throws ApiException {
        OffsetDateTime startDateTime = null;
        OffsetDateTime endDateTime = null;
        Boolean returnId = null;
        String apiVersion = null;
        api.apiMessageGetMOByDateGet(startDateTime, endDateTime, returnId, apiVersion);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiMessageGetMOGetTest() throws ApiException {
        Boolean returnId = null;
        String apiVersion = null;
        api.apiMessageGetMOGet(returnId, apiVersion);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiMessageSendGetTest() throws ApiException {
        String destinationAddress = null;
        String sourceAddress = null;
        String messageText = null;
        Boolean returnLongId = null;
        Integer port = null;
        String referenceNumberType = null;
        OffsetDateTime validityPeriod = null;
        String apiVersion = null;
        api.apiMessageSendGet(destinationAddress, sourceAddress, messageText, returnLongId, port, referenceNumberType, validityPeriod, apiVersion);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiMessageSendPostTest() throws ApiException {
        List<AradA2PMessage> body = null;
        Boolean returnLongId = null;
        String apiVersion = null;
        api.apiMessageSendPost(body, returnLongId, apiVersion);

        // TODO: test validations
    }
}
