///*
// * Arad SMS Core Api V1
// * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
// *
// * OpenAPI spec version: v1
// *
// *
// * NOTE: This class is auto generated by the swagger code generator program.
// * https://github.com/swagger-api/swagger-codegen.git
// * Do not edit the class manually.
// */
//
//package arad.itc.client.api;
//
//import com.mashape.unirest.http.HttpResponse;
//import com.mashape.unirest.http.Unirest;
//import com.mashape.unirest.http.exceptions.UnirestException;
//
//import arad.itc.client.ApiException;
//import arad.itc.client.Pair;
//import arad.itc.client.auth.Authentication;
//
//import org.junit.Test;
//import java.util.*;
//
//
//
///**
// * API tests for UserApi
// */
//
//
//
//
//public class UserApiTest {
//
//    private final UserApi api = new UserApi();
//
//    /**
//     *
//     *
//     *
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void apiUserUserInfoGetTest() throws ApiException {
//        String apiVersion = null;
//        api.apiUserUserInfoGet(apiVersion);
//
//        // TODO: test validations
//    }
//
//    public  static  String getToken( ) {
//
//        UserApi api = new UserApi();
//
//        String username = "username" ;
//        String password = "password" ;
//        String apiversion = "1" ;
//        Authentication authentication = api.getApiClient().getAuthentication("OAuth2") ;
//        ArrayList<Pair> arrayListQuery = new ArrayList();
//        HashMap HeaderHashMap = new HashMap();
//
//        arrayListQuery.add(new Pair("username",username));
//        arrayListQuery.add(new Pair("password",password));
//        HeaderHashMap.put("Content-Type","application/json");
//        HeaderHashMap.put("api-version", apiversion);
//        authentication.applyToParams(arrayListQuery,HeaderHashMap);
//
//        try {
//
//            api.apiUserUserInfoGet(apiversion);
//        } catch (ApiException e) {
//            throw new RuntimeException(e);
//        }
//
//        return " " ;
//    }
//
//    public static void main(String[] args) {
//
//        Unirest.setTimeouts(0, 0);
//        HttpResponse<String> response ;
//        try {
//             response = Unirest.post("https://api.aradvas.ir/connect/token")
//                   .header("Content-Type", "application/x-www-form-urlencoded")
//                   .field("username", "username")
//                   .field("password", "password")
//                   .asString();
//        } catch (UnirestException e) {
//            throw new RuntimeException(e);
//        }
//
//        System.out.println(response.getBody());
//
//    }
//}
